### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by zyuanbing** [alinlab/ifseg#5]
Excellent work! Thanks for the release.

I followed the instruction [here](https://github.com/alinlab/ifseg#image-processing) to perform image-free training on ADE20k val, but got extremely low mIoU results(0.0001). Below is my training log:

[logging.log](https://github.com/alinlab/ifseg/files/12094484/logging.log)

Is there any bug or possible wrong step in the training procedure that I performed? Or any hint?

Thanks in advance.

**Comment by kami93** [comment]
Hi. We have checked the codebase, however, the ADE20k results can be correctly reproduced as suggested in the following logs.
[logging.log](https://github.com/alinlab/ifseg/files/12475218/logging.copy.log)


Perhaps the wrong checkpoint file is being loaded in your case. When we run the ADE experiment with the Chinese-version OFA-base checkpoint, we could reproduce a similar log as given in your question. Please check.

Thanks!
